#!/bin/bash
function pause(){
    read -p "Press any key to continue..."
}

echo ~~~~~ \*nix Bukkit Plugin Generator ~~~~~

read -p "Enter your name: " USERNAME
read -p "Enter your plugin's name: " PLUGINNAME

echo "Will generate plugin: $PLUGINNAME by $USERNAME"
echo ""

pause

echo "Generating plugin..."
echo "";

BLOCKLISTENER=BlockListener.java
YBLOCKLISTENER=${PLUGINNAME}BlockListener.java

PLAYERLISTENER=PlayerListener.java
YPLAYERLISTENER=${PLUGINNAME}PlayerListener.java 

PLUGIN=YPlugin.java
YPLUGIN=${PLUGINNAME}.java
ENDPATH=${PLUGINNAME}/com/bukkit/${USERNAME}/${PLUGINNAME}

mkdir -p $ENDPATH
cd $ENDPATH

#touch ${PLUGINNAME}.java
#touch $YBLOCKLISTENER
#touch ${YPLAYERLISTENER}.java

cd ../../../../

echo "name: $PLUGINNAME

main: com.bukkit.$USERNAME.$PLUGINNAME

version: 0.1" > plugin.yml

cd ../files/

#cp $PLUGINYML ../${PLUGINNAME}/plugin.yml
sed -e "s/<yourname>/$USERNAME/g" -e "s/<pluginname>/$PLUGINNAME/g" $BLOCKLISTENER > ../${ENDPATH}/$YBLOCKLISTENER
sed -e "s/<yourname>/$USERNAME/g" -e "s/<pluginname>/$PLUGINNAME/g" $PLAYERLISTENER > ../${ENDPATH}/$YPLAYERLISTENER
sed -e "s/<yourname>/$USERNAME/g" -e "s/<pluginname>/$PLUGINNAME/g" $PLUGIN > ../${ENDPATH}/${PLUGINNAME}.java

echo ~~~~~~~~~~~~~~~~~~~ Done! ~~~~~~~~~~~~~~~
